swagger: '2.0'
info:
  title: forum
  description: |
    Тестовое задание для реализации проекта "Форумы" на курсе по базам данных в
    Технопарке Mail.ru (https://park.mail.ru).
  version: "0.1.0"
schemes:
  - http
  - https
basePath: /api
consumes:
  - application/json
produces:
  - application/json
paths:
  /forum/create:
      operationId: forumCreate
  /forum/{slug}/details:
      operationId: forumGetOne
  /forum/{slug}/create:
      operationId: threadCreate
  /forum/{slug}/users:
      operationId: forumGetUsers
  /forum/{slug}/threads:
      operationId: forumGetThreads

  /post/{id}/details:
      operationId: postGetOne
#      operationId: postUpdate


  /service/clear:
      operationId: clear
  /service/status:
      operationId: status

  /thread/{slug_or_id}/create:
      operationId: postsCreate
  /thread/{slug_or_id}/details:
      operationId: threadGetOne
#      operationId: threadUpdate
  /thread/{slug_or_id}/posts:
      operationId: threadGetPosts
  /thread/{slug_or_id}/vote:
      operationId: threadVote

  /user/{nickname}/create:
      operationId: userCreate
  /user/{nickname}/profile:
      operationId: userGetOne
#      operationId: userUpdate
